POST http://localhost:8080/api/chirps HTTP/1.1
content-type: application/json

{
    "body":"This is a different chirp with a different bad word - kerfuffle - .",
    "user_id":"a61683d1-c60a-4fb5-b47f-2d1903d4c2b5"
}